package lamport.payload;

public enum Request {
    VOID, READ, WRITE, PREWRITE,
    FAIL_READ, FAIL_WRITE, FAIL_PREWRITE,
    SUCCESS_WRITE, SUCCESS_READ,
    BUFFERED_READ, BUFFERED_WRITE, BUFFERED_PREWRITE,

    READ_CANCEL, WRITE_CANCEL, PREWRITE_CANCEL,
    SUCCESS_READ_CANCEL, SUCCESS_WRITE_CANCEL, SUCCESS_PREWRITE_CANCEL
}
